analytics: {}
color:
  brandColors:
    - '#D8C0E0'
    - '#202070'
    - '#885870'
    - '#2828A0'
    - '#F8B078'
  brandStrength: 0.77027
  lightness: 0.655405
  rhythmicContrast: 0.959459
  saturation: 0.672297
cta: {}
layout_spectrum: 0.938063
name: The Disco Dolls Studio
opengraph: {}
purpose: []
typography_spectrum: 0.467342
